/** @type {import('tailwindcss').Config} */
import animate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        neutral: {
          1: "var(--neutral-1)",
          2: "var(--neutral-2)",
          3: "var(--neutral-3)",
          4: "var(--neutral-4)",
          5: "var(--neutral-5)",
          6: "var(--neutral-6)",
          7: "var(--neutral-7)",
          8: "var(--neutral-8)",
          9: "var(--neutral-9)",
          10: "var(--neutral-10)",
          11: "var(--neutral-11)",
          12: "var(--neutral-12)",
          a1: "var(--neutral-a1)",
          a2: "var(--neutral-a2)",
          a3: "var(--neutral-a3)",
          a4: "var(--neutral-a4)",
          a5: "var(--neutral-a5)",
          a6: "var(--neutral-a6)",
          a7: "var(--neutral-a7)",
          a8: "var(--neutral-a8)",
          a9: "var(--neutral-a9)",
          a10: "var(--neutral-a10)",
          a11: "var(--neutral-a11)",
          a12: "var(--neutral-a12)",
        },

        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          1: "var(--accent-1)",
          2: "var(--accent-2)",
          3: "var(--accent-3)",
          4: "var(--accent-4)",
          5: "var(--accent-5)",
          6: "var(--accent-6)",
          7: "var(--accent-7)",
          8: "var(--accent-8)",
          9: "var(--accent-9)",
          10: "var(--accent-10)",
          11: "var(--accent-11)",
          12: "var(--accent-12)",
          a1: "var(--accent-a1)",
          a2: "var(--accent-a2)",
          a3: "var(--accent-a3)",
          a4: "var(--accent-a4)",
          a5: "var(--accent-a5)",
          a6: "var(--accent-a6)",
          a7: "var(--accent-a7)",
          a8: "var(--accent-a8)",
          a9: "var(--accent-a9)",
          a10: "var(--accent-a10)",
          a11: "var(--accent-a11)",
          a12: "var(--accent-a12)",
        },

        danger: {
          1: "var(--danger-1)",
          2: "var(--danger-2)",
          3: "var(--danger-3)",
          4: "var(--danger-4)",
          5: "var(--danger-5)",
          6: "var(--danger-6)",
          7: "var(--danger-7)",
          8: "var(--danger-8)",
          9: "var(--danger-9)",
          10: "var(--danger-10)",
          11: "var(--danger-11)",
          12: "var(--danger-12)",
          a1: "var(--danger-a1)",
          a2: "var(--danger-a2)",
          a3: "var(--danger-a3)",
          a4: "var(--danger-a4)",
          a5: "var(--danger-a5)",
          a6: "var(--danger-a6)",
          a7: "var(--danger-a7)",
          a8: "var(--danger-a8)",
          a9: "var(--danger-a9)",
          a10: "var(--danger-a10)",
          a11: "var(--danger-a11)",
          a12: "var(--danger-a12)",
        },

        success: {
          1: "var(--success-1)",
          2: "var(--success-2)",
          3: "var(--success-3)",
          4: "var(--success-4)",
          5: "var(--success-5)",
          6: "var(--success-6)",
          7: "var(--success-7)",
          8: "var(--success-8)",
          9: "var(--success-9)",
          10: "var(--success-10)",
          11: "var(--success-11)",
          12: "var(--success-12)",
          a1: "var(--success-a1)",
          a2: "var(--success-a2)",
          a3: "var(--success-a3)",
          a4: "var(--success-a4)",
          a5: "var(--success-a5)",
          a6: "var(--success-a6)",
          a7: "var(--success-a7)",
          a8: "var(--success-a8)",
          a9: "var(--success-a9)",
          a10: "var(--success-a10)",
          a11: "var(--success-a11)",
          a12: "var(--success-a12)",
        },

        warning: {
          1: "var(--warning-1)",
          2: "var(--warning-2)",
          3: "var(--warning-3)",
          4: "var(--warning-4)",
          5: "var(--warning-5)",
          6: "var(--warning-6)",
          7: "var(--warning-7)",
          8: "var(--warning-8)",
          9: "var(--warning-9)",
          10: "var(--warning-10)",
          11: "var(--warning-11)",
          12: "var(--warning-12)",
          a1: "var(--warning-a1)",
          a2: "var(--warning-a2)",
          a3: "var(--warning-a3)",
          a4: "var(--warning-a4)",
          a5: "var(--warning-a5)",
          a6: "var(--warning-a6)",
          a7: "var(--warning-a7)",
          a8: "var(--warning-a8)",
          a9: "var(--warning-a9)",
          a10: "var(--warning-a10)",
          a11: "var(--warning-a11)",
          a12: "var(--warning-a12)",
        },

        info: {
          1: "var(--info-1)",
          2: "var(--info-2)",
          3: "var(--info-3)",
          4: "var(--info-4)",
          5: "var(--info-5)",
          6: "var(--info-6)",
          7: "var(--info-7)",
          8: "var(--info-8)",
          9: "var(--info-9)",
          10: "var(--info-10)",
          11: "var(--info-11)",
          12: "var(--info-12)",
          a1: "var(--info-a1)",
          a2: "var(--info-a2)",
          a3: "var(--info-a3)",
          a4: "var(--info-a4)",
          a5: "var(--info-a5)",
          a6: "var(--info-a6)",
          a7: "var(--info-a7)",
          a8: "var(--info-a8)",
          a9: "var(--info-a9)",
          a10: "var(--info-a10)",
          a11: "var(--info-a11)",
          a12: "var(--info-a12)",
        },

        // shadcn/ui b&w theme
        border: "var(--border)",
        input: "hsl(var(--input))",
        ring: "var(--ring)",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        // overwritten because its part of internal component styling
        // destructive: {
        //   DEFAULT: "hsl(var(--destructive))",
        //   foreground: "hsl(var(--destructive-foreground))",
        // },
        destructive: {
          DEFAULT: "var(--danger-11)",
          foreground: "var(--neutral-1)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        // conflicts with my custom accent
        // accent: {
        //   DEFAULT: "hsl(var(--accent))",
        //   foreground: "hsl(var(--accent-foreground))",
        // },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [animate],
};
